# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Release

on:
  # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload-to-release:
    name: Upload to release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firefox
          path: web-ext-artifacts
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          file_glob: true
          file: ./web-ext-artifacts/mute_current_tab-${{ github.event.release.name }}.zip
          tag: ${{ github.ref }}
      - run: |
          echo "Upload to release successful:" >> $GITHUB_STEP_SUMMARY
          echo "mute_current_tab-${{ github.event.release.name }}.zip" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.event.release.html_url }}" >> $GITHUB_STEP_SUMMARY


  publish-to-mozilla:
    name: Publish to Mozilla Add-ons
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firefox
          path: web-ext-artifacts
      - uses: akoessler/release-firefox-addon@latest
        id: publish
        with:
          addon-id: '${{ secrets.MOZILLA_ADDONS_GUID }}'
          auth-api-issuer: ${{ secrets.MOZILLA_ADDONS_JWT_ISSUER }}
          auth-api-secret: ${{ secrets.MOZILLA_ADDONS_JWT_SECRET }}
          addon-path: ./web-ext-artifacts/mute_current_tab-${{ github.event.release.name }}.zip
          channel: listed
          license: MIT
          approval-note: |
            Source code is not modified during build.
            Available in src folder at: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}
            "npm run build" (web-ext build) to create zip package.
            "npm run run" (web-ext run) to debug the extension.
          release-note: |
            ${{ github.event.release.body }}
      - run: |
          echo "Publish to Mozilla Add-ons successful:" >> $GITHUB_STEP_SUMMARY
          echo "mute_current_tab-${{ github.event.release.name }}.zip" >> $GITHUB_STEP_SUMMARY
          echo "version: ${{ steps.publish.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "version-id: ${{ steps.publish.outputs.version-id }}" >> $GITHUB_STEP_SUMMARY
          echo "version-edit-url: ${{ steps.publish.outputs.version-edit-url }}" >> $GITHUB_STEP_SUMMARY
